---
# tasks file for tasktracker
- name: "Create directory for storing packages"
  file:
     path: /HadoopSoftwares
     state: directory
- name: "Download  JDK & Hadoop packages"
  get_url:
    url: "{{ item }}"
    dest: /HadoopSoftwares/
  loop: "{{ link }}"

- name: "Installing JDK & Hadoop packages"
  command: rpm -ivh /HadoopSoftwares/* --force
  ignore_errors: yes

- name: Configure mapred-site file
  template:
    src: "mapred-site.xml"
    dest: "/etc/hadoop/mapred-site.xml"

- name: Starting tasktracker service
  shell: "hadoop-daemon.sh start tasktracker"
  
- name: Making Hadoop Daemon Service Permanent
  lineinfile:
    path: /etc/rc.d/rc.local
    line: hadoop-daemon.sh start tasktracker
    mode: '0755'
- name: Check Status
  command: jps
  register: TaskTrackerStatus

- name: Status
  debug:
    var: TaskTrackerStatus.stdout_lines

