---
# tasks file for datanode
- name: "Create directory for storing packages"
  file:
     path: /HadoopSoftwares
     state: directory
- name: "Download  JDK & Hadoop packages"
  get_url:
    url: "{{ item }}"
    dest: /HadoopSoftwares/
  loop: "{{ link }}"

- name: "Installing JDK & Hadoop packages"
  command: rpm -ivh /HadoopSoftwares/* --force
  ignore_errors: yes
 
- name: Configure core-site file 
  template:
    src: "core-site.xml"
    dest: "/etc/hadoop/core-site.xml"

- name: Configure hdfs-site file 
  template:
    src: "hdfs-site.xml"
    dest: "/etc/hadoop/hdfs-site.xml"
        
- name: Starting namenode service
  shell: "hadoop-daemon.sh start datanode"
  
- name: Making Hadoop Daemon Service Permanent
  lineinfile:
    path: /etc/rc.d/rc.local
    line: hadoop-daemon.sh start datanode
    mode: '0755'
- name: Check Status
  command: jps
  register: DataNodeStatus

- name: Status
  debug: 
    var: DataNodeStatus.stdout_lines

